CREATE TYPE role AS ENUM ('ADMIN', 'TEACHER', 'STUDENT');

CREATE TABLE app_user (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	role role NOT NULL
);
