version: '3.7'

services:
  reverse_proxy:
    build:
      context: ./local-reverse-proxy
    ports:
      - 9080:80
    restart: always
  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    restart: always
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - 9600:8600
    environment:
      NODE_ENV: production
      PORT: 8600
      LOG_LEVEL: info
      JWT_SECRET: verylongrandomstring
      DB_HOST: host.docker.internal
      DB_PORT: 5442
      DB_USER: pg-user
      DB_PASSWORD: my-pg-password
      DB_NAME: my_postgres_db
      MODEL_SERVER_URL: http://host.docker.internal:8500
      SOLR_URL: http://host.docker.internal:8983
    restart: always
  flyway_migration:
    image: flyway/flyway:9.0.4-alpine
    entrypoint: ['sh', '-c', '/flyway/wait-for-it.sh postgres:5432 -- /flyway/flyway migrate']
    volumes:
      - ./packages/db/flyway/migrations:/flyway/sql
      - ./packages/db/flyway/afterMigrate.sql:/flyway/sql/afterMigrate.sql # Should I do this automatically or as another docker job?
      - ./packages/db/flyway/wait-for-it.sh:/flyway/wait-for-it.sh
    environment:
      FLYWAY_PASSWORD: my-pg-password
      FLYWAY_USER: pg-user
      FLYWAY_URL: jdbc:postgresql://postgres:5432/my_postgres_db
      FLYWAY_CONNECT_RETRIES: 180
  postgres:
    image: postgres:13.4-alpine
    ports:
      - 5442:5432
    environment:
      POSTGRES_PASSWORD: my-pg-password
      POSTGRES_USER: pg-user
      POSTGRES_DB: my_postgres_db
    volumes:
      - ./vol/postgres:/var/lib/postgresql/data
    restart: always
  solr:
    build:
      context: ./solr
    ports:
      - 8983:8983
    volumes:
      - ./vol/solr:/var/solr
    command: ['solr-precreate', 'submission-search', '/opt/solr-8.6.1/config']

networks:
  default:
    name: codeclusters-local
