version: '3.7'

services:
  test_data:
    build:
      context: ./db
      dockerfile: ./generator/Dockerfile
    container_name: test_data
    env_file:
      - .test_data.env
  flyway_migration:
    image: flyway/flyway:6.1.3-alpine
    container_name: flyway_migration
    entrypoint: ["sh", "-c", "/flyway/wait-for-it.sh postgres:5432 -- /flyway/flyway migrate"]
    volumes:
      - ./db/migrations:/flyway/sql
      - ./db/scripts/wait-for-it.sh:/flyway/wait-for-it.sh
    env_file:
      - .flyway.env
  flyway_seed:
    image: flyway/flyway:6.1.3-alpine
    container_name: flyway_seed
    entrypoint: ["sh", "-c", "/flyway/wait-for-it.sh postgres:5432 -- /flyway/flyway migrate"]
    volumes:
      - ./db/seed/afterMigrate.sql:/flyway/sql/afterMigrate.sql
      - ./db/scripts/wait-for-it.sh:/flyway/wait-for-it.sh
    env_file:
      - .flyway.env

networks:
  default:
    name: codeclusters-prod
